import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { FC } from 'react';
import Providers from './components/layout/Providers';
import Header from './components/layout/MainLayout/header';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'GTemgoua Portfolio',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en">
			<body
				className={`${roboto.className} min-h-[98dvh] overflow-scroll scrollbar-track-blue-500 scrollbar-thumb-white bg-white dark:bg-black text-primaryLight dark:text-primaryDark`}
			>
				<Providers>
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
