import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { FC } from 'react';
import Providers from '@/app/components/layout/Providers';
import Header from '@/app/components/layout/Header';
// import Footer from '@/app/components/layout/MainLayout/Footer';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'GTemgoua Portfolio',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en">
			<body className={`${roboto.className} bg-bgLight dark:bg-bgDark text-light dark:text-dark`}>
				<Providers>
					<Header />
					{children}
					{/* <Footer /> */}
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
